### ISSUE TITLE
拆元件

### ISSUE THREAD

**Issue by caasi** [miau715/lazy-island-planner#1]
現在所有的元件都放在 `index.js` 中，可以把 `MenuModes`, `MenuBtn`, `MenuTools`, `MenuItems` 拆到獨立的檔案裡看看？

**Comment by miau715** [comment]
應該拆好了 <(_ _)>

**Comment by caasi** [comment]
好快！

另外一個是命名方式，我看過一些元件命名方式，一是全大寫，例如 `MenuModes.js`, `MenuModes/index.js`, `menu-modes.js` ，之後可以參考看看～
